In [3]:
import pandas as pd
import numpy as np

data = pd.read_csv('02_complete-data-pop.csv', index_col='date', parse_dates=True)
data.head()

,Unnamed: 0,Unnamed: 0.1,Confirmed,country,Deaths,Last Update,Latitude,Longitude,province,Recovered,name,pop2020
date,,,,,,,,,,,,
2020-01-22,0,0,1.0,Mainland China,NaN,1/22/2020 17:00,NaN,NaN,Anhui,NaN,Mainland China,1439323.776
2020-01-22,1,1,14.0,Mainland China,NaN,1/22/2020 17:00,NaN,NaN,Beijing,NaN,Mainland China,1439323.776
2020-01-22,2,2,6.0,Mainland China,NaN,1/22/2020 17:00,NaN,NaN,Chongqing,NaN,Mainland China,1439323.776
2020-01-22,3,3,1.0,Mainland China,NaN,1/22/2020 17:00,NaN,NaN,Fujian,NaN,Mainland China,1439323.776
2020-01-22,4,4,NaN,Mainland China,NaN,1/22/2020 17:00,NaN,NaN,Gansu,NaN,Mainland China,1439323.776

In [6]:
data['Total'] = data.eval('Confirmed - Recovered')

In [7]:
data.head()

,Unnamed: 0,Unnamed: 0.1,Confirmed,country,Deaths,Last Update,Latitude,Longitude,province,Recovered,name,pop2020,Total
date,,,,,,,,,,,,,
2020-01-22,0,0,1.0,Mainland China,NaN,1/22/2020 17:00,NaN,NaN,Anhui,NaN,Mainland China,1439323.776,NaN
2020-01-22,1,1,14.0,Mainland China,NaN,1/22/2020 17:00,NaN,NaN,Beijing,NaN,Mainland China,1439323.776,NaN
2020-01-22,2,2,6.0,Mainland China,NaN,1/22/2020 17:00,NaN,NaN,Chongqing,NaN,Mainland China,1439323.776,NaN
2020-01-22,3,3,1.0,Mainland China,NaN,1/22/2020 17:00,NaN,NaN,Fujian,NaN,Mainland China,1439323.776,NaN
2020-01-22,4,4,NaN,Mainland China,NaN,1/22/2020 17:00,NaN,NaN,Gansu,NaN,Mainland China,1439323.776,NaN